[target.riscv32im-unknown-none-elf]
runner = ".cargo/flash.sh"
rustflags = [
  "-C", "link-arg=-Tmemory.x",
  "-C", "link-arg=-Tlink.x",
]

[unstable]
build-std = ["core", "compiler_builtins"]

[build]
target = "riscv32im-unknown-none-elf.json"
