[package]
name = "minerva-pac"
version = "0.1.0"
edition = "2021"

[dependencies]
riscv = "=0.9.0"
vcell = "=0.1.3"

critical-section = { version = "=1.1", optional = true }
riscv-rt = { version = "=0.10.0", optional = true }

[features]
rt = ["riscv-rt"]
